<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Kamus kode → label untuk data permohonan LAMA hasil migrasi
    |--------------------------------------------------------------------------
    |
    | Formulir baru menyimpan teks pilihannya apa adanya ("Islam"), tetapi
    | ribuan permohonan hasil migrasi menyimpan KODE ANGKA (agama "1",
    | pekerjaan "88"). Tanpa kamus ini, detail permohonan di dashboard petugas
    | dan PDF-nya menampilkan angka mentah alih-alih isi formulir.
    |
    | DIBANGKITKAN dari `lib/kode-options.ts` portal Next.js, yang sendirinya
    | dibangkitkan dari tabel `m_options` dump portal Laravel lama — sumber
    | kebenaran yang sama dengan dropdown formulir aslinya. Jangan disunting
    | manual; bangkitkan ulang bila dump berubah.
    |
    */

    'grup' => [
        'agama' => [
            '1' => 'Islam',
            '2' => 'Kristen',
            '3' => 'Katholik',
            '4' => 'Hindu',
            '5' => 'Budha',
            '6' => 'Konghuchu',
            '7' => 'Kepercayaan',
        ],
        'aktaPerceraianAlasan' => [
            '1' => 'Berbuat Zina',
            '2' => 'Pemabuk/Pemmadat',
            '3' => 'Penjudi',
            '4' => 'Meninggalkan Pasangan Lebih Dari 2 Tahun Tanpa Alasan',
            '5' => 'Hukuman Penjara Diatas 5 Tahun/Lebih Berat',
            '6' => 'Melakukan Kekejaman/Kekerasan Dalam Rumah Tangga',
            '7' => 'Mendapat Cacat Badan/Penyakit',
            '8' => 'Perselisihan/Pertengkaran Terus Menerus',
            '9' => 'Lainnya',
        ],
        'aktaPerceraianInstansiPemberiKeputusan' => [
            '1' => 'Pengadilan Negeri',
            '2' => 'Pengadilan Agama',
            '3' => 'Pengadilan Tinggi Negeri',
            '4' => 'Pengadilan Tinggi Agama',
            '5' => 'Mahkamah Agung',
        ],
        'aktaPerceraianYgMengajukan' => [
            '1' => 'Suami',
            '2' => 'Istri',
        ],
        'alasancetakulang' => [
            '1' => 'Hilang',
            '2' => 'Perubahan Kk',
            '3' => 'Rusak',
        ],
        'alasanKonsolidasiData' => [
            '1' => 'BPJS',
            '2' => 'Imigrasi',
            '3' => 'Kartu Pra-Kerja',
            '4' => 'Kepolisian',
            '5' => 'Perbankan',
            '6' => 'Telekomunikasi',
            '7' => 'Vaksin',
            '8' => 'Lainnya',
        ],
        'golongandarah' => [
            '1' => 'A',
            '2' => 'AB',
            '3' => 'AB-',
            '4' => 'AB+',
            '5' => 'A-',
            '6' => 'A+',
            '7' => 'B',
            '8' => 'B-',
            '9' => 'B+',
            '10' => 'O',
            '11' => 'O-',
            '12' => 'O+',
            '13' => 'Tidak Tahu',
        ],
        'jenisPerubahanBiodata' => [
            '0' => 'Nama Lengkap',
            '1' => 'Jenis Kelamin',
            '2' => 'Tempat Lahir',
            '3' => 'Tanggal Lahir',
            '4' => 'Golongan Darah',
            '5' => 'Agama',
            '6' => 'Pendidikan',
            '7' => 'Pekerjaan',
            '8' => 'Nama Ayah',
            '9' => 'Nama Ibu',
            '10' => 'Status Perkawinan',
        ],
        'jenkel' => [
            '0' => 'Perempuan',
            '1' => 'Laki-Laki',
        ],
        'kelahiranJenisKelahiran' => [
            '1' => 'Tunggal',
            '2' => 'Kembar Dua',
            '3' => 'Kembar Tiga',
            '4' => 'Kembar Empat',
            '5' => 'Kembar Banyak/Lainnya',
        ],
        'kelahiranPenolong' => [
            '1' => 'Dokter',
            '2' => 'Bidan/Perawat',
            '3' => 'Dukun',
            '4' => 'Lainnya',
        ],
        'kelahiranTempatdilahirkan' => [
            '1' => 'Rumah Sakit/Bersalin',
            '2' => 'Puskesmas',
            '3' => 'Polindes',
            '4' => 'Rumah',
            '5' => 'Lainnya',
        ],
        'kelahiranTempatPenyerahanDok' => [
            '1' => 'Kantor Disdukcapil',
            '2' => 'Kantor Kecamatan',
            '3' => 'pengiriman POS',
        ],
        'kematianMenerangkan' => [
            '1' => 'Dokter',
            '2' => 'Tenaga Kesehatan',
            '3' => 'Kepolisian',
            '4' => 'Lainnya',
        ],
        'kematianSebab' => [
            '1' => 'Sakit Biasa / Tua',
            '2' => 'Pandemi / Wabah Penyakit',
            '3' => 'Kecelakaan',
            '4' => 'Kriminalitas',
            '5' => 'Bunuh Diri',
            '6' => 'Lainnya',
        ],
        'kkNumpangAlasan' => [
            '1' => 'numpang KK suami',
            '2' => 'numpang KK family lain',
            '3' => 'numpang KK orang tua',
        ],
        'kkPisahAlasan' => [
            '1' => 'Sudah Nikah (Alamat Tetap)',
            '2' => 'Sudah Nikah (Alamat Pindah)',
            '3' => 'Belum Nikah (Alamat Tetap)',
            '4' => 'Belum Nikah (Alamat Pindah)',
            '5' => 'Sudah Cerai (Alamat Tetap)',
            '6' => 'Sudah Cerai (Alamat Pindah)',
            '7' => 'Sudah Cerai & Nikah (Alamat Tetap)',
            '8' => 'Sudah Cerai & Nikah (Alamat Pindah)',
            '9' => 'Cerai Mati (Alamat Tetap)',
            '10' => 'Cerai Mati (Alamat Pindah)',
        ],
        'kkPisahJenis' => [
            '1' => 'Kepala Keluarga',
            '2' => 'KK & sebagian anggota keluarga',
            '3' => 'KK & seluruh anggota keluarga',
            '4' => 'Anggota Keluarga',
        ],
        'ktpElAlasan' => [
            '1' => 'Rusak',
            '2' => 'Hilang',
            '3' => 'Masih Suket',
            '4' => 'Baru/Pemula',
            '5' => 'Penduduk Datang',
            '6' => 'Perubahan Data',
        ],
        'pekerjaan' => [
            '1' => 'Belum/Tidak Bekerja',
            '2' => 'Mengurus Rumah Tangga',
            '3' => 'Pelajar/Mahasiswa',
            '4' => 'Pensiunan',
            '5' => 'Pegawai Negeri Sipil',
            '6' => 'Tentara Nasional Indonesia',
            '7' => 'Kepolisian Ri',
            '8' => 'Perdagangan',
            '9' => 'Petani/Pekebun',
            '10' => 'Peternak',
            '11' => 'Nelayan/Perikanan',
            '12' => 'Industri',
            '13' => 'Konstruksi',
            '14' => 'Transportasi',
            '15' => 'Karyawan Swasta',
            '16' => 'Karyawan Bumn',
            '17' => 'Karyawan Bumd',
            '18' => 'Karyawan Honorer',
            '19' => 'Buruh Harian Lepas',
            '20' => 'Buruh Tani/Perkebunan',
            '21' => 'Buruh Nelayan/Perikanan',
            '22' => 'Buruh Peternakan',
            '23' => 'Pembantu Rumah Tangga',
            '24' => 'Tukang Cukur',
            '25' => 'Tukang Listrik',
            '26' => 'Tukang Batu',
            '27' => 'Tukang Kayu',
            '28' => 'Tukang Sol Sepatu',
            '29' => 'Tukang Las/Pandai Besi',
            '30' => 'Tukang Jahit',
            '31' => 'Tukang Gigi',
            '32' => 'Penata Rias',
            '33' => 'Penata Busana',
            '34' => 'Penata Rambut',
            '35' => 'Mekanik',
            '36' => 'Seniman',
            '37' => 'Tabib',
            '38' => 'Paraji',
            '39' => 'Perancang Busana',
            '40' => 'Penterjemah',
            '41' => 'Imam Mesjid',
            '42' => 'Pendeta',
            '43' => 'Pastor',
            '44' => 'Wartawan',
            '45' => 'Ustadz/Mubaligh',
            '46' => 'Juru Masak',
            '47' => 'Promotor Acara',
            '48' => 'Anggota Dpr-Ri',
            '49' => 'Anggota Dpd',
            '50' => 'Anggota Bpk',
            '51' => 'Presiden',
            '52' => 'Wakil Presiden',
            '53' => 'Anggota Mahkamah Konstitusi',
            '54' => 'Anggota Kabinet/Kementerian',
            '55' => 'Duta Besar',
            '56' => 'Gubernur',
            '57' => 'Wakil Gubernur',
            '58' => 'Bupati',
            '59' => 'Wakil Bupati',
            '60' => 'Walikota',
            '61' => 'Wakil Walikota',
            '62' => 'Anggota Dprd Provinsi',
            '63' => 'Anggota Dprd Kabupaten/Kota',
            '64' => 'Dosen',
            '65' => 'Guru',
            '66' => 'Pilot',
            '67' => 'Pengacara',
            '68' => 'Notaris',
            '69' => 'Arsitek',
            '70' => 'Akuntan',
            '71' => 'Konsultan',
            '72' => 'Dokter',
            '73' => 'Bidan',
            '74' => 'Perawat',
            '75' => 'Apoteker',
            '76' => 'Psikiater/Psikolog',
            '77' => 'Penyiar Televisi',
            '78' => 'Penyiar Radio',
            '79' => 'Pelaut',
            '80' => 'Peneliti',
            '81' => 'Sopir',
            '82' => 'Pialang',
            '83' => 'Paranormal',
            '84' => 'Pedagang',
            '85' => 'Perangkat Desa',
            '86' => 'Kepala Desa',
            '87' => 'Biarawati',
            '88' => 'Wiraswasta',
            '89' => 'Lainnya',
        ],
        'pendidikan' => [
            '1' => 'Tidak/Belum Sekolah',
            '2' => 'Belum Tamat SD/Sederajat',
            '3' => 'Tamat SD/Sederajat',
            '4' => 'SLTP/Sederajat',
            '5' => 'SLTA/Sederajat',
            '6' => 'Diploma I/II',
            '7' => 'Akademi/Diploma III',
            '8' => 'Diploma IV/Strata I',
            '9' => 'Strata II',
            '10' => 'Strata III',
        ],
        'pindahPendudukJenis' => [
            '1' => 'Kepala Keluarga',
            '2' => 'KK & sebagian anggota keluarga',
            '3' => 'KK & seluruh anggota keluarga',
            '4' => 'Anggota Keluarga',
        ],
        'pindahPendudukKlasifikasi' => [
            '1' => 'Dalam Satu Desa / Kelurahan',
            '2' => 'Antar Desa / Kelurahan',
            '3' => 'Antar Kecamatan',
            '4' => 'Antar Kabupaten / Kota',
            '5' => 'Provinsi',
        ],
        'statusperkawinan' => [
            '1' => 'Belum Kawin',
            '2' => 'Kawin',
            '3' => 'Cerai Hidup',
            '4' => 'Cerai Mati',
        ],
    ],

    /*
    | Nama field payload → grup di atas. Beberapa field berbeda nama namun
    | berbagi daftar pilihan yang sama (mis. pekerjaan pemohon/suami/istri).
    */
    'field' => [
        'agama' => 'agama',
        'pekerjaan' => 'pekerjaan',
        'pekerjaanistri' => 'pekerjaan',
        'pekerjaansuami' => 'pekerjaan',
        'pendidikan' => 'pendidikan',
        'statusperkawinan' => 'statusperkawinan',
        'golongandarah' => 'golongandarah',
        'jeniskelamin' => 'jenkel',
        'jenisbiodata' => 'jenisPerubahanBiodata',
        'tempatdilahirkan' => 'kelahiranTempatdilahirkan',
        'jeniskelahiran' => 'kelahiranJenisKelahiran',
        'penolong' => 'kelahiranPenolong',
        'menerangkankematian' => 'kematianMenerangkan',
        'sebabkematian' => 'kematianSebab',
        'alasancerai' => 'aktaPerceraianAlasan',
        'instansipemberiputusan' => 'aktaPerceraianInstansiPemberiKeputusan',
        'yangmengajukan' => 'aktaPerceraianYgMengajukan',
        'alasankonsolidasidata' => 'alasanKonsolidasiData',
        'alasancetakulang' => 'alasancetakulang',
        'alasancetak' => 'ktpElAlasan',
        'alasannumpangkk' => 'kkNumpangAlasan',
        'alasanpisah' => 'kkPisahAlasan',
        'jenispisah' => 'kkPisahJenis',
        'jeniskepindahan' => 'pindahPendudukJenis',
        'klasifikasikepindahan' => 'pindahPendudukKlasifikasi',
    ],

];
